### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by anxuae** [pibooth/pibooth-google-photo#1]
Hello @sravel ,

I've just finished the creation of a new plugin [pibooth-extra-lights](https://github.com/pibooth/pibooth-extra-lights). With this one, I have made a "standardized structure" for plugins in order to publish them on pypi. As plugin from pypi are automatically detected by `pibooth` at startup, it ease the plugins installation.

I propose to do the same for this plugin, are you agree with that?
If yes, I can propose a PR, or I let you do it.

**Comment by sravel** [comment]
Hello,
Yes i agree to standardize plugins
I have never created a program use by Pypi, so I am interested in trying to do it.
I'm going to rely on the pibooth-extra-lights plugin to do it.
I also saw that the plugins doc was updated, I will make the modifications to be in agreement with.
it may be necessary to review the code, but I will do, no problem.
I try during the week.

**Comment by anxuae** [comment]
Nice! I will be happy to help you.

Here are some recommendations:
 - the setup.py from `pibooth-extra-lights` should have few modification (import, author is you and requirements)
 - there is bad indentations in your plugin (should be 4 spaces)
 - don't use `format` when you use `LOGGER`, use for instance `LOGGER.info("Bla black %s", myvars)`
 - the credentials file should not be commited in the repo, it  is generated by the user and its path should be defined in the config
 - adding 2 new options in a new section of the config should be enough : `[GOOGLE][gallery_name]` and `[GOOGLE][credentials_file]` (see example of `pibooth_configure` hook)

**Comment by anxuae** [comment]
To release your plugin on pypi, here is small guide that I made for `pibooth`: https://github.com/pibooth/pibooth/blob/master/docs/release.rst

**Comment by sravel** [comment]
Ok I think it's good.
I keep your name on Authors because you help me and I use your template.
I also add pibooth>=2.0.0 dependency, so plugin can be use only when you build the release. (but I test on my dev version)
https://pypi.org/project/pibooth-google-photo/1.0.1/

**Comment by anxuae** [comment]
Hi @sravel ,

Good job!
I have few comments:

- The version number does not corresponds to the one in PyPI (1.0.1):
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L14

- The default value should be empty string instead of `'client_id.json'`:
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L25

- the `try... except:...` block is useless because, if the key is not defined in the config, the `cfg.get(...)` will return the default value that you have defined in the `add_option`
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L32-L35

- use `cfg.getpath('GOOGLE', 'client_id_file')` which process relative paths and convert them to absolute ones
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L33

- check path is not empty (default value should be `""`). Instead of exiting the program, You can set `app.google_photo = None` and check it in `state_processing_exit` hook. Like that, the plugin can be installed, and `pibooth` can start even if the credential file is not configured (we can imagine that sometime, we want disable the upload)
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L35-L37

- The `try... except:...` block is useless
https://github.com/pibooth/pibooth-google-photo/blob/814407360af07a48a54df46ad6fd7fac67130a05/pibooth_google_photo.py#L44-L46

**Comment by sravel** [comment]
Thank for review. I change code with your comment.
I want to append option on menu to enable/disable the upload, can you help me?
I see you append config on parser DEFAULT dict with function add_option
can you append 2 params like this:
```python
def add_option(self, section, option, default, description, menu_name=None, menu_option=None):
        """Add a new option to the configuration.

        :param section: section in which the option is declared
        :type section: str
        :param option: option name
        :type option: str
        :param default: default value of the option
        :type default: any
        :param description: description to put in the configuration
        :type description: str
        :param menu_name: name on menu
        :type menu_name: str
        :param menu_option: choice on menu
        :type menu_option: any
        """
        assert section, "Section name can not be empty string"
        assert option, "Option name can not be empty string"
        assert description, "Description can not be empty string"

        # Find the caller plugin
        stack = inspect.stack()
        if len(stack) < 2:
            plugin_name = "Unknown"
        else:
            plugin = inspect.getmodule(inspect.stack()[1][0])
            plugin_name = get_plugin_name(self._pm, plugin, False)

        # Check that the option is not already created
        if section in DEFAULT and option in DEFAULT[section]:
            raise ValueError("The plugin '{}' try to define the option [{}][{}] "
                             "which is already defined.".format(plugin_name, section, option))

        # Add the option to the default dictionary
        description = "{}\n# Required by '{}' plugin".format(description, plugin_name)
        DEFAULT.setdefault(section, odict())[option] = (default, description, menu_name, menu_option)
```
and change on menu.py like this:
```python
        # for name in ('GENERAL', 'WINDOW', 'PICTURE', 'PRINTER'):
        for name in DEFAULT.keys():
            if name not in ['CONTROLS', 'CAMERA']:
```
So I can make something like this
```python
    cfg.add_option('GOOGLE', 'activate', True, "Option to allow disable plugin",
                   "activate", ['True', 'False'])
```

**Comment by anxuae** [comment]
I will do it
