### ISSUE TITLE
Access to picture URL uploaded on google Photos

### ISSUE THREAD

**Issue by DennisD88** [pibooth/pibooth-google-photo#10]
Is it possible when the photo is uploaded to Google Photo that they scan a qr code with the link to the specifc photo?

I know a part of the link https://photos.google.com/share/**AxFF4t56kiJiu89m**/2021-06-11-10-14-08_pibooth.jpg

But what is the part between the stars?

**Comment by sravel** [comment]
Hello I also want to do link to the specific photo, but without success... I don't see on google API how do that.
sorry

**Comment by anxuae** [comment]
See PR

**Comment by DennisD88** [comment]
Hi, I update the plugins of the QRcode and the Google Photo. What are the next steps what I must setup?

**Comment by anxuae** [comment]
Hi @DennisD88 ,

See my comment here: https://github.com/pibooth/pibooth-qrcode/issues/15
