### ISSUE TITLE
error pibooth

### ISSUE THREAD

**Issue by chonchon033** [pibooth/pibooth-google-photo#11]
bonjour 
J'ai un message erreur 
Can not load [GOOGLE][client_id_file]='/home/pi/.config/pibooth/client_id":""4319.....................................' please check config
Pouvez vous m'aider àse probleme.
Merci Beaucoup

**Comment by anxuae** [comment]
Hi @chonchon033 could we have the full logs?

**Comment by anxuae** [comment]
Please test with the new version and post the logs
