### ISSUE TITLE
Question: Link for access single picture Google Photos

### ISSUE THREAD

**Issue by mhilcher** [pibooth/pibooth-google-photo#13]
Hi,

first thank you for your work, I appreciate that a lot.

I did all the steps and created my own app with the Google Photos Api enabled.
I downloaded the credentials and Pibooth was authorized by the Api, so that Pibooth has access.
The photos are uploaded to Google Photos into the correct album.

Now when I want to access this photo directly via a shared link, it doesn't work.
I used several urls, e.g. :
'https://photos.app.goo.gl/{mySharedSecret}/{picture_name}.jpg' or 'https://photos.google.com/share/{mySharedSecret}/{picture_name}.jpg'

I only can see the complete album and then click on the photo to show or download it.

Do you know if there is a way to generate a link that directly points to the photo without having to show the album first?
I want to show a QR code after each taken picture that points exactly to this photo, so that the people can download the photo from there.

Thank you and best wishes,
Martin

**Comment by sravel** [comment]
See this issue
https://github.com/pibooth/pibooth-google-photo/issues/10

**Comment by mhilcher** [comment]
Hi, I just saw that this issue is duplicated with #10 
Sorry, will have a look into the closed issues next time before writing...
