### ISSUE TITLE
Looks like it's always a first connection

### ISSUE THREAD

**Issue by Aurel-Charles** [pibooth/pibooth-google-photo#15]
Hi guys, each time I launch the pibooth app, it ask me to grant the access through the link . I do it but it keeps asking every time I close and relaunch.
I using " sudo pibooth " as I've got led's that works only as root user
Any suggestion?

beside that it works great. Thx a lot!!!

**Comment by anxuae** [comment]
Hi,

Can you run pibooth in verbose mode and past the logs?

```
sudo pibooth -v
```

**Comment by Aurel-Charles** [comment]
where do I find the log?

**Comment by anxuae** [comment]
In the console where you launch the command

**Comment by Aurel-Charles** [comment]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ DEBUG   ] pibooth           : Plugin found at '/home/pi/plugin_pibooth_neopixel.py'
[ INFO    ] pibooth           : Installed plugins: qrcode-1.0.2, google-photo-1.2.2, extra-lights-1.0.1, plugin_pibooth_neopixel-?.?.?
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B+
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
[ DEBUG   ] pibooth           : Fallback to pibooth default camera management system
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ INFO    ] pibooth           : Initialize Google Photos connection
[ DEBUG   ] urllib3.connectionpool: Starting new HTTPS connection (1): photos.google.com:443
[ DEBUG   ] urllib3.connectionpool: https://photos.google.com:443 "HEAD / HTTP/1.1" 302 0
[ DEBUG   ] pibooth           : Application key or secret has changed, store new token in file '/root/.config/pibooth/.google_token.json'
[ DEBUG   ] requests_oauthlib.oauth2_session: Generated new state qhXLa1dlDPf71EBnqWrNlnVHrAPCqw.
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1027010349442-7lrdkvhsuldde4hct433a9p2ceunsnbj.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A35515%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&state=qhXLa1dlDPf71EBnqWrNlnVHrAPCqw&access_type=offline

**Comment by anxuae** [comment]
New version 1.2.3 published to fix the issue. Please close issue when confirmed

**Comment by Aurel-Charles** [comment]
All good! Thx a lot man.
