### ISSUE TITLE
Trouble with API authorization

### ISSUE THREAD

**Issue by Martouf0208** [pibooth/pibooth-google-photo#20]
Hi everyone !

I'm trying to use the librairie my problem is when the browser page is opening for authorize the API, after login to google he said me that the application isn't verifed.

![20230514_134739](https://github.com/pibooth/pibooth-google-photo/assets/64268543/59b36f00-f239-44c4-8c20-dc51f692a47a)

If someone is able to help me, thanks !

**Comment by sravel** [comment]
Hello, 
yes it's completely normal, pibooth is not an official application so for security reasons, google asks if we are sure to give the rights.
To validate you must go to advanced settings and validate the authorization

**Comment by Martouf0208** [comment]
Thanks @sravel for the reply, can you guide me to make the authorization, I'm a newbie with API, did I need to enable access transparancy, if yes I need to create an organisation.
Thanks

**Comment by anxuae** [comment]
So issue seems to be resolved.
