### ISSUE TITLE
Cannot disable google-photo plugin

### ISSUE THREAD

**Issue by lxne** [pibooth/pibooth-google-photo#21]
Hi, I am trying to disable the plugin with pibooth --config.

I added 'google-photo' to 'plugins_disabled' but google photos is still active.

```
# Plugin names to be disabled after startup (list of quoted names accepted)
plugins_disabled = 'google-photo'
```

Am I missing something?

**Comment by werdeil** [comment]
Hi @lxne did you try with its full name: `pibooth-google-photo` ?

**Comment by lxne** [comment]
> Hi @lxne did you try with its full name: `pibooth-google-photo` ?

Thank you. I tried this now, but the plugin still's not disabled.

This is not a google-photo issue, because I cannot disable any of my plugins.

**Comment by werdeil** [comment]
I've just tested and with the right name disabling plugins works (however the plugin are still shown as installed in the log.

Right name for the plugin is `pibooth_google_photo` with underscores.

**Comment by lxne** [comment]
I didn't realize that it has to be with underscores.
Thank you.
