### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by Jjbp6440** [pibooth/pibooth-google-photo#3]
Hello,
first of all thanks for all the work done on pibooth it's just amazing!

I tried to install the plugin but it's impossible because I don't have the pibooth 2.00. but the pibooth 2.0 doesn't seems to exist yet (even you updated all the documentation with the new version). could you have a look please?
thanks in advance

message:
`pip3 install pibooth-google-photo

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pibooth-google-photo
  Using cached https://files.pythonhosted.org/packages/ac/65/ce5d8a403690df32de221aac4aa4fa23717ce9020448f0e27da001a43918/pibooth_google_photo-1.0.1-py2.py3-none-any.whl
Collecting pibooth>=2.0.0 (from pibooth-google-photo)
  Could not find a version that satisfies the requirement pibooth>=2.0.0 (from pibooth-google-photo) (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0)
No matching distribution found for pibooth>=2.0.0 (from pibooth-google-photo)

`

**Comment by werdeil** [comment]
Hello pibooth 2.0.0 is still in development and I don’t know when we will release it, in the meantime yu can install the developmbt version.

**Comment by Jjbp6440** [comment]
> Hello pibooth 2.0.0 is still in development and I don’t know when we will release it, in the meantime yu can install the developmbt version.

ah ok, as the documentation was updated with the V2 I was not completely sure. 
![Capture d’écran 2020-05-21 à 23 42 07](https://user-images.githubusercontent.com/64653180/82609387-bfaa7e00-9bbc-11ea-968f-b140d741a686.png)

my wedding is only in October so I have time to wait the official release (I just start raspberry and python... ;) )
thanks for you explanation!

**Comment by sravel** [comment]
Hello if you want to test the development version you can install as Dev
for pibooth use this https://github.com/pibooth/pibooth/issues/142
or this
https://github.com/pibooth/pibooth/blob/master/docs/dev.rst
and for pibooth-google-photo 
```bash
git clone https://github.com/pibooth/pibooth-google-photo.git
cd pibooth-google-photo
sudo python3 -m pip install --editable .

if fail try to change the setup line 47 to
```python
            'pibooth>=1.2.0',
```

**Comment by Jjbp6440** [comment]
Hello,
ok I will try! but when I tried to install the dev branche of pibooth yesterday it's doesn't work! it stayed on V1.2... I don't know why. I will retry.

Do you have an idea when the V2 will be be released?
thanks for you help and all the work!

**Comment by sravel** [comment]
Yes the dev version still on "1.2.0" when you install.
For the 2.0.0 release, I'm not the developer of pibooth, I just  add some help/idea and make this plugin so I have no idea for the date.
But @anxuae and @werdeil  make a good work and generally dev version have sometime just minor bug, so try your Pibooth !!!!
If you want to update the dev version (ie there is more recent commit on git) just go to folder clone and write
```
git pull
```

**Comment by Jjbp6440** [comment]
ok I will try that!
stupid question how could I use your plugin even the dev version still under 1.2 ? because it's required 2.0 (sorry I'm new with all this staff!)

**Comment by anxuae** [comment]
Hi @Jjbp6440 

I've change the version number in the dev branch to solve your issue.
Please re-install the dev version of pibooth

**Comment by Jjbp6440** [comment]
Perfect I will try later on this  weekend I don’t have access to the raspberry now
Thanks for your help!

**Comment by Jjbp6440** [comment]
hello Guys,

Thanks for your help! it's working.
I just had to delete everything and to reinstall it! now my pictures are in google photo.
I will play like that until you deliver the stable version
Thanks for your great work! once everything is build I will share on the wiki some pictures!
Have a nice sunday!
