### ISSUE TITLE
error 400: redirect_uri_mismash

### ISSUE THREAD

**Issue by klemva** [pibooth/pibooth-google-photo#6]
Hi guys,
at first i have to thank you for Pibooth and your plugins. It is awsome app!!!! Realy greate work!

But i have issue with google plug in.

I stuck on authorization. I can't authorizate, because i show me error 400: redirect_uri_mismash.

When i create Credentials - OAuth client ID in Api&Services, i can choose only Web application, Android, Chrome app, iOS, TVs and Limited Input devices, Desktop app and Universal Windows Platform(UWP). I found in google manual, that Other was replaced by Web Application. Next it want Authorized JavaScript origins and Authorized redirect URIs. If i have booth empty, it show me my error 400: redirect_uri_mismash. The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit:..........link to console.developers.google.com.

I tried to add authorized URIs to JavaScript and for request from a web server, but without success.

Could you please help with it?

Thank you

Václav from Czech Republic

**Comment by sravel** [comment]
Hi, 
When you create Credentials did you use Desktop app?
![image](https://user-images.githubusercontent.com/11534773/119472114-3a672580-bd4a-11eb-8420-a895e532b9c0.png)

**Comment by klemva** [comment]
Yes, I tried, but it shows error 403:access_denied.

The developer hasn't given you access to this app. It's currently being tested and it hasn't`t beed verified by Google. If you think you should have access, contact the developer(my email).

**Comment by anxuae** [comment]
Hi @klemva 

If fact, you just have to follow instructions when you click on the `Enable the Google Photos Library API`  of the link : https://developers.google.com/photos/library/guides/get-started

Choose `Desktop app` and it should works

**Comment by anxuae** [comment]
Issue seems closed, please re-open if you still need help.
