### ISSUE TITLE
[ ERROR   ] pibooth           : ('invalid_grant: Bad Request',

### ISSUE THREAD

**Issue by ttette** [pibooth/pibooth-google-photo#9]
Thanks a lot for the great plug in for the PiBooth.

It used to work perfectly but recently after updating the Pibooth to the latest version I cannot make the google photo upload work any more.

I followed the instruction to get the API activated and to get the client ID and secret.

When I run the photobooth and the plug in tries to upload the photo I get the following message:

[ INFO    ] pibooth           : Use OpenCvPictureFactory to assemble final image
[ INFO    ] pibooth           : Use OpenCvPictureFactory to draw texts
[ INFO    ] pibooth           : Save image '/home/pi/Pictures/pibooth/2021-08-26-15-29-30_pibooth.jpg'
[ ERROR   ] pibooth           : ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

i never got the google authentication screen when first starting plug-in.

I have no idea what I'm missing :( can someone please help

Thanks !

**Comment by sravel** [comment]
Hello, 
do you have a "google_credentials.dat" file in the same directory as the "credentials.json" file? 

can you try to generate OAuth client file with this:
https://developers.google.com/photos/library/guides/get-started#request-id

**Comment by ttette** [comment]
Hi sravel,

thanks for having a look and sorry for taking me so long to answer - I managed to lock the case of my photo booth and then lose the key :D, so only managed to take it apart today.

I have the google_credentials.dat file in the same folder as the .json, but when trying to generate the OAuth client file I only get the option to download the "credentials.json", do I didn't even update the "google_credentials.dat". 

So, should I just manually update the "google_credentials.dat" or there is another way to generate via the google API console?

Again many thanks for looking into this, much appreciated!

Todor

**Comment by anxuae** [comment]
Hi @ttette did you solved your issue?

**Comment by anxuae** [comment]
Please re-open if necessary
